### ISSUE TITLE
Mentioning Denoised Smoothing?

### ISSUE THREAD

**Issue by sayakpaul** [tensorflow/neural-structured-learning#100]
Recently Denoised Smoothing was added under `research/third_party`. Is it possible to mention it from the [Research](https://github.com/tensorflow/neural-structured-learning#research) section on the README?

**Comment by arjung** [comment]
Yeah, we can add a line there. I think it would also be good to add an entry in https://github.com/tensorflow/neural-structured-learning/tree/master/research/README.md with more details  about that project. Would you be willing to send us a PR?

**Comment by sayakpaul** [comment]
Just did: https://github.com/tensorflow/neural-structured-learning/pull/105.

I also noticed some entries are either missing or not synced in the two entries. For example, `multi_representation_adversary` is not present in either of the repositories.

**Comment by arjung** [comment]
Closing this per https://github.com/tensorflow/neural-structured-learning/pull/105
