### ISSUE TITLE
Should we expect NSL to work with 2.0?

### ISSUE THREAD

**Issue by samedii** [tensorflow/neural-structured-learning#18]
Based on #9 I'm guessing maybe we should not expect it to work? Edit: #3 suggests that 2.0 should work however.

The example code on https://www.tensorflow.org/neural_structured_learning is not working with 2.0 but it works with 1.15

Note that when running tf-nightly-gpu you get the message:
`TensorFlow's `tf-nightly` package will soon be updated to TensorFlow 2.0. `

**Comment by samedii** [comment]
Okay, sadly none of the examples work even after trying for a little while. I will continue trying then. Thank you!

**Comment by DualityGap** [comment]
Feel free to reopen this issue and maybe provide specific error you have encountered, so we can have more in-depth discussion.
