### ISSUE TITLE
Issue with fit() function - problem with passing model containing multiple inputs

### ISSUE THREAD

**Issue by jasiozaucha** [tensorflow/neural-structured-learning#19]
While using standalone Keras my model worked fine but when I try adding adversarial regularisation I run into trouble with passing the inputs (I tried many ways but nothing works). 

The details of my model are irrelevant but I must say that it has two separate inputs which are joined together later. The standard Keras model which worked looked like this:
`input0 = Input(shape=(50,3), name='input_A')`
`input1 = Input(shape=(50,30),name='input_B')`
(...intermediate-layers...)
`output0=GlobalMaxPooling1D(name='output')(output0)`
 `model=Model(inputs=[input0,input1],outputs=[output0])`
I successfully trained this model by passing two separate dictionaries:
`model.fit({'input_A':train[i][0] ,'input_B':train[i][1]} ,{'output':train[i][-1]})`
Note that the first dimension of train (i) is just used to chunk up the training into smaller sets that will fit into memory (in this case 801838 data instances). So train[0][0] is shape (801838,50,3), while train[0][1] is shape (801838,50,30). 

Then I tried adding adversarial regularisation, straight from the demo:
`adv_model = nsl.keras.AdversarialRegularization(model, label_keys=['label'])`
But when I try running fit() there are always problems when I attempt to pass the inputs:
1. Passing the two inputs in a list does not work: 
`adv_model.fit(x={'features':[train[i][0] ,train[i][1]],'label':train[i][-1]})`
ValueError: could not broadcast input array from shape (801838,50,3) into shape (801838,50)
2. A single dictionary produces the following error:
`adv_model.fit(x={'input_A':train[i][0] ,'input_B':train[i][1],'label':train[i][-1]})`
ValueError: Layer model_1 was called with an input that isn't a symbolic tensor. Received type: <type 'dict'>. Full input: [{'input_B': <tf.Tensor 'input_B_1:0' shape=(?, 50, 30) dtype=float32>, 'input_A': <tf.Tensor 'input_A_1:0' shape=(?, 50, 3) dtype=float32>}]. All inputs to the layer should be tensors.
3. I also tried a nested dictionary:
`adv_model.fit(x={'features':{'input_A':train[i][0] ,'input_B':train[i][1]},'label':train[i][-1]})`
ValueError: Cannot create a tensor proto whose content is larger than 2GB.
4. Passing in the labels separately as before:
`adv_model.fit(x={'input_A':train[i][0] ,'input_B':train[i][1]},y={'label':train[i][-1]})`
ValueError: Labels are not in the input. For predicting examples without labels, please use the base model instead.

Can anyone help me?

**Comment by csferng** [comment]
@jasiozaucha, what is your TensorFlow version?

`AdversarialRegularization` expects inputs being passed like your method (2), i.e. a single dictionary containing all of feature and label tensors. For example, the following script (adapted from your snippets) can be run on Tensorflow 2.0.0rc2 and 1.15.0rc1 without error:

```python
import neural_structured_learning as nsl
import numpy as np
import tensorflow as tf

input0 = tf.keras.Input(shape=(3, 2), name='input_A')
input1 = tf.keras.Input(shape=(3, 5), name='input_B')
concat = tf.keras.layers.Concatenate()([input0, input1])
flat = tf.keras.layers.Flatten()(concat)
output0 = tf.keras.layers.Dense(1, name='output')(flat)

batch_size = 7
x0 = np.random.random((batch_size, 3, 2))
x1 = np.random.random((batch_size, 3, 5))
y = np.random.random((batch_size, 1))

model = tf.keras.Model(inputs=[input0, input1], outputs=[output0])
adv_model = nsl.keras.AdversarialRegularization(model, label_keys=['label'])
adv_model.compile('sgd', loss='mse')
adv_model.fit({'input_A': x0, 'input_B': x1, 'label': y})
```

**Comment by jasiozaucha** [comment]
Hi csferng, thank you for your answer. My version 2 does appear similar to your toy example. 
The toy example unfortunately also does not run correctly. But the error I get at the fit step is: 
"AttributeError: 'AdversarialRegularization' object has no attribute '_sample_weight_modes'"
My tf version is 1.11, so I guess the first step is to get my sysadmin to update tensor flow... I let you know how I get along with it.

**Comment by csferng** [comment]
@jasiozaucha, please let us know if you still face the issue after updating TensorFlow.

BTW, if you are interested, you could also try [`virtualenv`](https://virtualenv.pypa.io/en/latest/) to create an isolated Python environment and to install a different version of TensorFlow (and other packages) from your host system.

**Comment by jasiozaucha** [comment]
Yes, it is an issue with the tensor flow version. The update resolved the problem so you can close this issue. Perhaps, when installing neural structured learning you should indicate to users that it is critical to update tensor flow. Thank you for your help!

**Comment by csferng** [comment]
Glad that the problem is resolved, and thanks for your suggestion.
