### ISSUE TITLE
Examples with genomic and medical data

### ISSUE THREAD

**Issue by xhlulu** [tensorflow/neural-structured-learning#2]
Hello,

I'm really excited to try this library out. Particularly, I noticed this from the article:

> The graphs can come from multiple sources such as Knowledge graphs, medical records, genomic data or multimodal relations (e.g., image-text pairs). 

Do you know if there is any existing examples using medical records? Thanks!

**Comment by esparza83** [comment]
Is there a particular format when combining with  ImageDataGenerator?   
Error:
OperatorNotAllowedInGraphError: iterating over `tf.Tensor` is not allowed in Graph execution

**Comment by arjung** [comment]
@xhlulu, Thanks for your interest in our framework! We don't have an example that uses medical records. You can do one of the following two depending on whether you already have a graph or not:

1. If you have such data represented explicitly as a graph, then you can convert it into a TSV format, which our framework expects.You can then run the ['pack_nbrs'](https://www.tensorflow.org/neural_structured_learning/api_docs/python/nsl/tools/pack_nbrs) program to generate input that is required for graph-based NSL. See our [tutorial](https://www.tensorflow.org/neural_structured_learning/tutorials/graph_keras_mlp_cora) that demonstrates the use of NSL for classifying documents that form a graph.

2. If you don't have an explicit graph and want to construct a graph, you can use our [graph builder](https://www.tensorflow.org/neural_structured_learning/api_docs/python/nsl/tools/build_graph), which expects a dense representation/embedding for each instance. See our [tutorial](https://www.tensorflow.org/neural_structured_learning/tutorials/graph_keras_lstm_imdb) for an example that builds a graph from text input and subsequently uses NSL for classification.

**Comment by xhlulu** [comment]
Thank you!
