### ISSUE TITLE
Add __version__ (PEP 396)

### ISSUE THREAD

**Issue by ageron** [tensorflow/neural-structured-learning#25]
This project should expose its version as `nsl.__version__` to respect [PEP 396](https://www.python.org/dev/peps/pep-0396/).

```pycon
>>> import neural_structured_learning as nsl
>>> nsl.__version__
[...]
AttributeError: module 'neural_structured_learning' has no attribute '__version__'
```

**Comment by csferng** [comment]
Thanks for the suggestion. We will include `__version__` in the next release.
