### ISSUE TITLE
ImportError: cannot import name 'configs' from 'neural_structured_learning'

### ISSUE THREAD

**Issue by ivan-vasilev** [tensorflow/neural-structured-learning#36]
After installing neural_structured_learning with pip, I can successfully do:

import neural_structured_learning as nsl

But when I try:

from neural_structured_learning import configs

I get the following error:
ImportError: cannot import name 'configs' from 'neural_structured_learning'

I'm using python 3.7

**Comment by DualityGap** [comment]
You should be able to invoke the config module by 'nsl.configs' (instead of a separate importing).

**Comment by arjung** [comment]
@ivan-vasilev, I tried importing `configs` the way you did and it worked for me. Below is sample output from a python shell.

`
Python 3.7.5rc1 (default, Oct  2 2019, 04:19:31) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import neural_structured_learning as nsl
>>> from neural_structured_learning import configs
>>> 
`

**Comment by arjung** [comment]
Closing the issue as we don't think there is a bug here.
