### ISSUE TITLE
Graphnet, GraphSage comparison

### ISSUE THREAD

**Issue by boraturant** [tensorflow/neural-structured-learning#38]
Hi,

Any comment on how NSL positioned with respect to DeepMind's Graphnet, or Graphsage?

**Comment by litaxc** [comment]
Also interested in this topic.

**Comment by DualityGap** [comment]
Hey Bora & Lita,

Thank you for your interests in NSL : )

First, NSL is [a TF library and part of TF ecosystem](https://www.tensorflow.org/neural_structured_learning), which means users can enjoy all the nice features (eager execution, Keras APIs, distributed training, etc) from TF2.0 when using NSL. NSL also provides [graph tools](https://www.tensorflow.org/neural_structured_learning/api_docs/python/nsl/tools) for users to construct & parse the graphs.

In terms of graph algorithms, NSL currently focuses on [graph regularization](https://www.tensorflow.org/neural_structured_learning/framework) and related techniques. 
From my personal understanding, GraphSage focuses more on learning node embeddings by using random walk, and Graphnet is to provide fundamental operations for users to build custom models.

We do have an ambition to include more graph algorithms & models in the NSL framework : ) You are welcome to suggest graph algorithms that you want to play with when using the NSL framework.
