### ISSUE TITLE
minor issue

### ISSUE THREAD

**Issue by sezan92** [tensorflow/neural-structured-learning#39]
i saw some code mistake in the tensorflow blog of nsl. how can i correct it?

**Comment by arjung** [comment]
Thanks @sezan92 . Could you provide more information on what the mistake is? I don't think you'd be able to edit the blog yourself.

**Comment by sezan92** [comment]
here, https://medium.com/tensorflow/introducing-neural-structured-learning-in-tensorflow-5a802efd7afd
```
adv_model = nsl.keras.AdversarialRegularization(model, adv_config)
````
This line is mistake. i checked the source code. the adv_config should be third argument. second argument is a dict.

**Comment by csferng** [comment]
Thanks @sezan92 for reporting the issue. The `adv_config` is intended to be a keyword argument, so that line should be
```python
adv_model = nsl.keras.AdversarialRegularization(model, adv_config=adv_config)
```
We will update the blog post soon.

**Comment by csferng** [comment]
The blog post has been updated.
