### ISSUE TITLE
NSL vs graphical neural network?

### ISSUE THREAD

**Issue by byronyi** [tensorflow/neural-structured-learning#43]
Thanks for open sourcing NSL! Recent contribution activity looks very promising for an open source project.

I am no expert in NSL. In the past, I see multiple existing projects trying to provide building blocks for graphical neural networks:

* [GraphNets](https://github.com/deepmind/graph_nets)
* [Deep Graph Library](https://www.dgl.ai/)
* [Torch-Geometric](https://github.com/rusty1s/pytorch_geometric)
* [Euler](https://github.com/alibaba/euler)
* [Torch-BigGraph](https://github.com/facebookresearch/PyTorch-BigGraph)

Would you mind to explain a little bit more (preferably in the project description) what is the difference between NSL and (other) graphical neural network abstractions? I believe that it would be very helpful for many users to decide which library to start with for building deep models on graphs.

**Comment by DualityGap** [comment]
Hey Bairen,

Thanks for the great question : )

First, NSL is a [TF library and part of TF ecosystem](https://www.tensorflow.org/neural_structured_learning), which means users can enjoy all the nice features (eager execution, Keras APIs, distributed training, etc) from TF2.0 when using NSL.
Several libraries you mentioned are implemented in other platforms such as PyTorch.

In terms of graph algorithms, NSL currently focuses on [graph regularization](https://www.tensorflow.org/neural_structured_learning/framework) and related techniques. We do have an ambition to include more graph algorithms & models in the NSL framework : ) You are welcome to suggest graph algorithms that you want to play with when using the NSL framework.
