### ISSUE TITLE
Possible for NSL to be use in Seq2seq setting?

### ISSUE THREAD

**Issue by joelowj** [tensorflow/neural-structured-learning#48]
Hi Team,

I chanced upon NSL framework and would like to say that this is an amazing work. I am currently working on some Structured Prediction task and would like to explore this framework. But I am not too clear if is is possible for this framework can be extended to say a Seq2Seq problem? Based on your experience and familiarity is it possible to do so? At the moment, is it possible for me to pack more than 1 graph and augment it with the training set?

**Comment by DualityGap** [comment]
Thanks for the question, Joel : )

Yes, it is possible to extend this framework to Seq2Seq problems.
For example, see Figure 1(D) in this [paper](https://arxiv.org/pdf/1703.04818.pdf).
A graph can be used to regularize the output of an encoder, and then this encoder output (embedding) will be sent to the decoder in a Seq2Seq setting.

Regarding your 2nd question, packing more than one graph may require some light-weight modifications on [pack neighbors](https://www.tensorflow.org/neural_structured_learning/api_docs/python/nsl/tools/pack_nbrs) to incorporate more than one graph : )

**Comment by joelowj** [comment]
@DualityGap cool, thanks a lot for the clarification. Have a nice day!
