### ISSUE TITLE
node classification [blogcatalog]

### ISSUE THREAD

**Issue by snash4** [tensorflow/neural-structured-learning#5]
Hello, 
 Could you please share the experimental code of classification of nodes on blogcatalog dataset. It would be very helpful to understand the NSL framework. 
Thanks.

**Comment by arjung** [comment]
We don't have an example that uses the blogcatalog dataset. To understand how the NSL framework can be used, we recommend going through our [tutorials](https://github.com/tensorflow/neural-structured-learning/tree/master/g3doc/tutorials).

**Comment by snash4** [comment]
I was referring to the node classification experiment on blog-catalog in the paper. 
What I understood from Figure 1(B)  from the paper is that you follow the edge model (Xi, Xj) i.e two FFNs and in the last layer, you perform the graph regularization. Correct me if I am wrong. 
But, in the tutorial of Cora dataset, there is only one FFN with graph regularization which is different what the paper shows. 
Please help me understand what I am missing

**Comment by arjung** [comment]
Graph regularization using NSL is a generic technique and is not tied to the neural network architecture (such as FFNN with a set number of layers). Also, in a graph-regularized model, there is just one neural network/model, and neighbors of samples are passed through the same network as the samples themselves.

Hope this makes sense.
