### ISSUE TITLE
About the version of tensorflow

### ISSUE THREAD

**Issue by Luogaorong** [tensorflow/neural-structured-learning#60]
Hi,
I had a problem running your code.You can say which version of tensorflow you use?

thkans!

**Comment by arjung** [comment]
HI @Luogaorong, can you share more specifics on the problem you ran into? Which version of TF were you using and how were you using NSL?

Graph regularization in NSL does not work with TF 2.1.0. Since the latest TF version, which is 2.2.0,  was recently released, all our tutorials use that version.
