### ISSUE TITLE
An example of similarity search

### ISSUE THREAD

**Issue by sayakpaul** [tensorflow/neural-structured-learning#89]
I was wondering if the team would be interested to work on a tutorial to show how NSL could be used for similarity and retrieval tasks using the graph APIs provided by NSL. Would be even interesting to benchmark the performance of that against other nearest neighbors' approaches. 

I personally think it would be helpful for many developers working in this area.

**Comment by arjung** [comment]
NSL currently does not have APIs to retrieve nearest neighbors. It has APIs to build a graph based on dense embeddings using locality sensitive hashing. You might be interested in https://github.com/google-research/google-research/tree/master/scann.
