### ISSUE TITLE
Will NSL work with TensorFlow 1.x ?

### ISSUE THREAD

**Issue by itxiud2015** [tensorflow/neural-structured-learning#9]
I can see NSL work with TensorFlow 2.0, what about the earlier version of TensorFlow, for example the TensorFlow 1.4? Thanks.

**Comment by arjung** [comment]
Thanks for the question, @itxiud2015. I think you meant TensorFlow 1.14 in your comment. NSL requires TensorFlow v 1.15 (currently available with the '[tf-nightly](https://pypi.org/project/tf-nightly/)' build) or higher. We will update our documentation shortly to explicitly mention this.
