### ISSUE TITLE
FB237 ids

### ISSUE THREAD

**Issue by PhaelIshall** [tensorflow/neural-structured-learning#90]
Hello, 

I have a question that I hope you can answer. Why are the downloaded files for FB237 containing entity and relation ids that are different from the ones with the original dataset? I am trying to test a model trained on the data from kbc repository with some of the original data converted to ids and they are not the same. Could you please provide information on how you created the ids?

**Comment by arjung** [comment]
Hi @ines-chami, could you help answer this? Thanks!

**Comment by ines-chami** [comment]
Hi, 
We actually reused the data files released in the kbc open source repository: 
https://github.com/facebookresearch/kbc/blob/master/kbc/scripts/download_data.sh

This issue about ids may help: https://github.com/facebookresearch/kbc/issues/17

**Comment by arjung** [comment]
Thanks for the response, Ines!
