### ISSUE TITLE
Our CVPR tutorial and its use of Neural Structured Learning

### ISSUE THREAD

**Issue by sayakpaul** [tensorflow/neural-structured-learning#91]
Hi folks.

I wanted to let y'all know about our CVPR 2021 tutorial "Practical Adversarial Robustness in Deep Learning: Problems and Solutions (PAR)" organized by Pin-Yu Chen (IBM Research) and myself. 

We made use of Neural Structured Learning in this tutorial extensively and wanted you to know about that. Code, slides, and videos of our tutorial are all available here: https://sites.google.com/view/par-2021. Was wondering if it's possible to give it a mention? 

Our code is distributed as Colab Notebooks.

**Comment by arjung** [comment]
Hi @sayakpaul, wonderful to know about your tutorial and that you've used NSL extensively :). We're planning to create a dedicated page or a separate section of the README to document such external usage of NSL. We'd be happy to list this tutorial and related material there. Feel free to also let me know if you have given other tutorials, talks, etc, on NSL and would like to list them there.

Will keep this issue open until we have that structure in place (rough ETA 1-2 weeks).

**Comment by sayakpaul** [comment]
Thank you so much!

**Comment by arjung** [comment]
Thanks for your patience! We now have a dedicated page to document feature usage: https://github.com/tensorflow/neural-structured-learning/blob/master/usage.md, and I've already included your CVPR tutorial. Let me know if there is any other workshop/tutorial/presentation that you're aware of that should be added here. I am closing this issue now.

**Comment by sayakpaul** [comment]
Thanks, @arjung. The tutorial on Recognizing Multimodal Entailment looks super (especially very comprehensive). Do you folks plan to release the videos soon?

**Comment by arjung** [comment]
I believe so but I am not a 100% sure yet. If they become available, will definitely link them here.
