### ISSUE TITLE
Mention the use-cases from the homepage?

### ISSUE THREAD

**Issue by sayakpaul** [tensorflow/neural-structured-learning#99]
The [official introduction page](https://www.tensorflow.org/neural_structured_learning/framework) lists a couple of tutorials with NSL:

![image](https://user-images.githubusercontent.com/22957388/130180234-015f1797-c6c3-47e4-a033-5d0099930d5a.png)

I think it would make sense to also mention a few community-contributed resources there. NSL already has a [`usage.md`](https://github.com/tensorflow/neural-structured-learning/blob/master/usage.md) page. Could be reused here.

**Comment by arjung** [comment]
We discussed this earlier this week and our plan is to add a reference to https://github.com/tensorflow/neural-structured-learning/tree/master/neural_structured_learning/examples from that page to direct users to other examples/notebooks demonstrating NSL. I'll assign this issue to myself for getting that done.

**Comment by sayakpaul** [comment]
That's good. But I think that directory is incomplete as it does not mention the other works that use NSL heavily. If somehow that `usage.md` page could also be facilitated that would be even better.

**Comment by arjung** [comment]
The goal of this section is to point users to examples and notebooks to help them get started with NSL. I think the 'examples' directory should be sufficient for that in addition to the list shown above but perhaps we'll add a pointer to `usage.md` too -- will check with the team on that. We certainly wouldn't want to duplicate what's in `usage.md` on our TF webpage though.

**Comment by sayakpaul** [comment]
Yeah understood. Anything to enhance the visibility of the external use-cases could be accommodated. I believe you folks will definitely figure that out :)

**Comment by arjung** [comment]
In https://github.com/tensorflow/neural-structured-learning/commit/dd44cce3a7f386fbaf49c90c28415fa2747f820a , we added links to the [examples](https://github.com/tensorflow/neural-structured-learning/tree/master/neural_structured_learning/examples) directory from https://www.tensorflow.org/neural_structured_learning/framework as well as from our top-level README file. So, am closing this issue.
